#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'g03-prii3-turtlesim','console_scripts','auto_turtle'
__requires__ = 'g03-prii3-turtlesim'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('g03-prii3-turtlesim', 'console_scripts', 'auto_turtle')()
    )
